# Generated by Django 3.1.5 on 2021-01-28 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('zip', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='User Email', max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, help_text=' User First Name', max_length=255)),
                ('last_name', models.CharField(blank=True, help_text='User Last Name', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', help_text='Gender choice M, F, O, U', max_length=16)),
                ('birth_date', models.DateField(help_text=' Date of birth of user', null=True)),
                ('contact_address', models.OneToOneField(blank=True, default=None, help_text='User Contact address related to address class ', null=True, on_delete=django.db.models.deletion.CASCADE, to='social.address')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headline', models.CharField(help_text='Post headline', max_length=255, unique=True)),
                ('content', models.TextField(help_text='Post content')),
                ('published', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('S', 'Social'), ('P', 'Personal'), ('I', 'International'), ('SP', 'Sports'), ('F', 'Fun'), ('UI', 'Unidentified')], default='UI', help_text='Category choice S, P, I, F, SP, UI', max_length=16)),
                ('like', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Posts authored by user', on_delete=django.db.models.deletion.CASCADE, related_name='user_post', related_query_name='user_posts', to='social.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.CharField(choices=[('LU', 'Like up'), ('LD', 'Like Down'), ('NL', 'No Like')], default='NL', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='Post being liked on', on_delete=django.db.models.deletion.CASCADE, related_name='post_like', related_query_name='post_likes', to='social.posts')),
                ('user', models.ForeignKey(help_text='User likes to the post', on_delete=django.db.models.deletion.CASCADE, related_name='user_like', related_query_name='user_likes', to='social.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_content', models.TextField(help_text='Post content')),
                ('comment_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='Post being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comments', to='social.posts')),
            ],
        ),
    ]
